apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: NodePort
  selector:
    app: supportapp
  ports:
  - name: ui
    port: 8501
    targetPort: 8501
    nodePort: 30001    # Access UI at localhost:30001
