name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/Intelligent-Customer-Support-Automation-Using-NLP

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Show workspace
      run: ls -R ${{ github.workspace }}

    - name: Set working directory
      run: |
        cd ${{ github.workspace }}/Intelligent-Customer-Support-Automation-Using-NLP
        ls -la

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest

    - name: Lint with pylint
      run: |
        pylint app || true

    - name: Run tests
      run: |
        pytest -v


